/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complexmathbinarycalculator;

import java.awt.event.ActionEvent;
import javax.swing.JFrame;

/**
 *
 * @author oscar
 */
public class NumberPane extends javax.swing.JPanel{

    /**
     * Creates new form NumberPane
     */
    public NumberPane() {
        this.real1="";
        this.real2="";
        this.imaginary1="";
        this.imaginary2="";
        initComponents();
    }
    
    public void setWindow(Window window){
        this.window=window;
    }
    public void setCalculator(Calculator calculator){
        this.calculator=calculator;
    }
    public void setReal1(String real1){
        this.real1=real1;
    }
    public void setReal2(String real2){
        this.real2=real2;
    }
    public void setImaginary1(String imaginary1){
        this.imaginary1=imaginary1;
    }
    public void setImaginary2(String imaginary2){
        this.imaginary2=imaginary2;
    }
    public String getReal1(){
        return this.real1;
    }
    public String getReal2(){
        return this.real2;
    }
    public String getImaginary1(){
        return this.imaginary1;
    }
    public String getImaginary2(){
        return this.imaginary2;
    }
    public void resetAll(){
        this.real1="";
        this.real2="";
        this.imaginary1="";
        this.imaginary2="";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt0 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btDot = new javax.swing.JButton();
        btI = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btDot.setText(".");
        btDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDotActionPerformed(evt);
            }
        });

        btI.setText("i");
        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btDot, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDot, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        this.number=7;
        this.numberCases();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        this.number=8;
        this.numberCases();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        this.number=9;
        this.numberCases();
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        this.number=6;
        this.numberCases();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        this.number=5;
        this.numberCases();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        this.number=4;
        this.numberCases();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        this.number=3;
        this.numberCases();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        this.number=2;
        this.numberCases();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        this.number=1;
        this.numberCases();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        this.number=0;
        this.numberCases();
    }//GEN-LAST:event_bt0ActionPerformed

    private void btDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDotActionPerformed
        switch(this.window.getState()){
            case 0: 
                    this.real1+="0.";
                    this.calculator.setReal1(Float.parseFloat(this.real1));
                    this.window.setState(3);
                    this.window.refreshTFWindow();
                    break;
            case 1:
                    this.real1+="0.";
                    this.calculator.setReal1(Float.parseFloat(this.real1));
                    this.window.setState(3);
                    this.window.refreshTFWindow();
                    break;
            case 2: 
                    this.real1+=".";
                    this.calculator.setReal1(Float.parseFloat(this.real1));
                    this.window.setState(3);
                    this.window.refreshTFWindow();
                    break;
            case 4:
                    this.imaginary1+="0.";
                    this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));
                    this.window.setState(7);
                    this.window.refreshTFWindow();
                    break;
            case 5:
                    this.imaginary1+="0.";
                    this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));
                    this.window.setState(7);
                    this.window.refreshTFWindow();
                    break;
            case 6:
                    this.imaginary1+=".";
                    this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));
                    this.window.setState(7);
                    this.window.refreshTFWindow();
                    break;
            case 8:
                    this.real2+="0.";
                    this.calculator.setReal2(Float.parseFloat(this.real2));
                    this.window.setState(11);
                    this.window.refreshTFWindow();
                    break;
            case 9:
                    this.real2+="0.";
                    this.calculator.setReal2(Float.parseFloat(this.real2));
                    this.window.setState(11);
                    this.window.refreshTFWindow();
                    break;
            case 10:
                    this.real2+=".";
                    this.calculator.setReal2(Float.parseFloat(this.real2));
                    this.window.setState(11);
                    this.window.refreshTFWindow();
                    break;
            case 12:
                    this.imaginary2+="0.";
                    this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                    this.window.setState(15);
                    this.window.refreshTFWindow();
                    break;
            case 13:
                    this.imaginary2+="0.";
                    this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                    this.window.setState(15);
                    this.window.refreshTFWindow();
                    break;
            case 14:
                    this.imaginary2+=".";
                    this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                    this.window.setState(15);
                    this.window.refreshTFWindow();
                    break;
        }
    }//GEN-LAST:event_btDotActionPerformed

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        switch(this.window.getState()){
            case 0:
                    this.window.setState(4);
                    this.window.refreshTFWindow();
                    break;
            case 2:
                    this.window.setState(4);
                    this.window.refreshTFWindow();
                    break;
            case 3:
                    this.window.setState(4);
                    this.window.refreshTFWindow();
                    break;
            case 8:
                    this.window.setState(12);
                    this.window.refreshTFWindow();
                    break;
            case 10:
                    this.window.setState(12);
                    this.window.refreshTFWindow();
                    break;
            case 11:
                    this.window.setState(12);
                    this.window.refreshTFWindow();
                    break;
        }
    }//GEN-LAST:event_btIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btDot;
    private javax.swing.JButton btI;
    // End of variables declaration//GEN-END:variables
    private Window window;
    private Calculator calculator;
    private String real1,
                   real2,
                   imaginary1,
                   imaginary2;
    private int number;
    
    
    private void numberCases(){
         switch(this.window.getState()){
                case 0:
                       this.real1+=number;
                       this.calculator.setReal1(Float.parseFloat(this.real1));
                       this.window.setState(2);     
                       this.window.refreshTFWindow();
                       break;
                case 1:
                       this.real1+=number;
                       this.calculator.setReal1(Float.parseFloat(this.real1));
                       this.window.setState(2);                       
                       this.window.refreshTFWindow();
                       break;
                case 2:
                       this.real1+=number;
                       this.calculator.setReal1(Float.parseFloat(this.real1));
                       this.window.setState(2); 
                       this.window.refreshTFWindow();
                       break;
                case 3:
                       this.real1+=number;
                       this.calculator.setReal1(Float.parseFloat(this.real1));
                       this.window.setState(3);
                       this.window.refreshTFWindow();
                       break;
                case 4: 
                       this.imaginary1+=number;
                       this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));   
                       this.window.setState(6);
                       this.window.refreshTFWindow();
                       break;
                case 5:
                       this.imaginary1+=number;
                       this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));                       
                       this.window.setState(6); 
                       this.window.refreshTFWindow();
                       break;
                case 6: 
                       this.imaginary1+=number;
                       this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));                       
                       this.window.setState(6); 
                       this.window.refreshTFWindow();
                       break;
                case 7: 
                        this.imaginary1+=number;
                        this.calculator.setImaginary1(Float.parseFloat(this.imaginary1));                       
                        this.window.setState(7);
                        this.window.refreshTFWindow();
                        break;
                case 8:
                        this.real2+=number;
                        this.calculator.setReal2(Float.parseFloat(this.real2));
                        this.window.setState(10);                       
                        this.window.refreshTFWindow();
                        break;
                case 9: 
                        this.real2+=number;
                        this.calculator.setReal2(Float.parseFloat(this.real2));
                        this.window.setState(10);
                        this.window.refreshTFWindow();
                        break;
                case 10:
                        this.real2+=number;
                        this.calculator.setReal2(Float.parseFloat(this.real2));
                        this.window.setState(10);
                        this.window.refreshTFWindow();
                        break;
                case 11:
                        this.real2+=number;
                        this.calculator.setReal2(Float.parseFloat(this.real2));
                        this.window.setState(11);
                        this.window.refreshTFWindow();
                        break;
                case 12:
                        this.imaginary2+=number;
                        this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                        this.window.setState(14);
                        this.window.refreshTFWindow();
                        break;
                case 13:
                        this.imaginary2+=number;
                        this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                        this.window.setState(14);
                        this.window.refreshTFWindow();
                        break;
                case 14:
                        this.imaginary2+=number;
                        this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                        this.window.setState(14);
                        this.window.refreshTFWindow();
                        break;
                case 15:
                        this.imaginary2+=number;
                        this.calculator.setImaginary2(Float.parseFloat(this.imaginary2));
                        this.window.setState(15);
                        this.window.refreshTFWindow();
                        break;
         }
    }
}
