/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complexmathbinarycalculator;

import javax.swing.JFrame;

/**
 *
 * @author oscar
 */
public class OperationPane extends javax.swing.JPanel {

    /**
     * Creates new form OperationPane
     */
    public OperationPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAC = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();
        btRes = new javax.swing.JButton();
        btEqual = new javax.swing.JButton();
        btMult = new javax.swing.JButton();
        btSum = new javax.swing.JButton();

        btAC.setText("AC");
        btAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btACActionPerformed(evt);
            }
        });

        btDiv.setText("/");
        btDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivActionPerformed(evt);
            }
        });

        btRes.setText("-");
        btRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResActionPerformed(evt);
            }
        });

        btEqual.setText("=");
        btEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEqualActionPerformed(evt);
            }
        });

        btMult.setText("X");
        btMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultActionPerformed(evt);
            }
        });

        btSum.setText("+");
        btSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btAC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSum, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btEqual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btMult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSum, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setNumberPane(NumberPane numberPane){
        this.numberPane=numberPane;
    }
    public void setWindow(Window window){
        this.window=window;
    }
    public void setCalculator(Calculator calculator){
        this.calculator=calculator;
    }
    
    
    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
        this.window.setState(0);
        this.numberPane.resetAll();
        this.calculator.resetAll();
        this.window.refreshTFWindow();
    }//GEN-LAST:event_btACActionPerformed

    private void btDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivActionPerformed
        this.operator="/";
        this.operatorCases();
    }//GEN-LAST:event_btDivActionPerformed

    private void btResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResActionPerformed
        this.operator="-";
        switch(this.window.getState()){
            case 0 :
                this.numberPane.setReal1("-");
                this.calculator.setReal1(Float.parseFloat("-0"));
                this.window.setState(1);
                break;
            case 2:
                this.window.setState(8);
                this.window.setOperator("-");
                break;
            case 3:
                this.window.setState(8);
                this.window.setOperator("-");
                break;    
            case 4:
                this.numberPane.setImaginary1("-");
                this.calculator.setImaginary1(Float.parseFloat("-0"));
                this.window.setState(5);
                break;
            case 6:
                this.window.setState(8);
                this.window.setOperator("-");
                break;
            case 7:
                this.window.setState(7);
                this.window.setOperator("-");
                break;
            case 8:
                this.numberPane.setReal2("-");
                this.calculator.setReal2(Float.parseFloat("-0"));
                this.window.setState(9);
                break;
            case 12:
                this.numberPane.setImaginary2("-");
                this.calculator.setImaginary2(Float.parseFloat("-0"));
                this.window.setState(13);
                break;
        }
        this.window.refreshTFWindow();
    }//GEN-LAST:event_btResActionPerformed

    private void btEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEqualActionPerformed
        switch(this.window.getState()){
            case 15:
                this.calculator.selectOperation(this.window.getOperator());
                this.window.refreshTFWindow();
                break;
            case 14:
                this.calculator.selectOperation(this.window.getOperator());
                this.window.refreshTFWindow();
                break;
            case 11:
                this.calculator.selectOperation(this.window.getOperator());
                this.window.refreshTFWindow();
                break;
            case 10:
                this.calculator.selectOperation(this.window.getOperator());
                this.window.refreshTFWindow();
                break;
        }
            
    }//GEN-LAST:event_btEqualActionPerformed

    private void btMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultActionPerformed
        this.operator="*";
        this.operatorCases();
    }//GEN-LAST:event_btMultActionPerformed

    private void btSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumActionPerformed
        this.operator="+";
        this.operatorCases();
    }//GEN-LAST:event_btSumActionPerformed
    
    private void operatorCases(){
        switch(this.window.getState()){
            case 2:
                this.window.setState(8);
                this.window.setOperator(this.operator);
                this.window.refreshTFWindow();
                break;
            case 3:
                this.window.setState(8);
                this.window.setOperator(this.operator);
                this.window.refreshTFWindow();
                break;
            case 6:
                this.window.setOperator(this.operator);
                this.window.setState(8);
                this.window.refreshTFWindow();
                break;
            case 7:
                this.window.setOperator(this.operator);
                this.window.setState(8);
                this.window.refreshTFWindow();
                break;
        }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAC;
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btEqual;
    private javax.swing.JButton btMult;
    private javax.swing.JButton btRes;
    private javax.swing.JButton btSum;
    // End of variables declaration//GEN-END:variables
    private Window window;
    private Calculator calculator;
    private String operator;
    private NumberPane numberPane;
}
