/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complexmathbinarycalculator;

import javax.swing.JTextField;

/**
 *
 * @author oscar
 */
public class Window extends javax.swing.JFrame {
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.state=0;
        this.real1="";
        this.real2="";
        this.imaginary1="";
        this.imaginary2="";
        this.operator="";
        this.calculator=new Calculator();
        this.numberPane.setWindow(this); 
        this.numberPane.setCalculator(this.calculator);
        this.operationPane.setNumberPane(this.numberPane);
        this.operationPane.setWindow(this);  
        this.operationPane.setCalculator(this.calculator);
    }
    /**
     this method sets the variable state, which is used as shown in the 
     diagram state**/
    @Override
    public void setState(int state){
        this.state=state;
    }
    @Override
    public int getState(){
        return this.state;
    }
    public void setOperator(String operator){
        this.operator=operator;
    }
    public void setReal1(String real1){
        this.real1=real1;
    }
    public void setReal2(String real2){
        this.real2=real2;
    }
    public void setImaginary1(String imaginary1){
        this.imaginary1=imaginary1;
    }
    public void setImaginary2(String imaginary2){
        this.imaginary2=imaginary2;
    }
    public String getOperator(){
        return this.operator;
    }
    
     public void refreshTFWindow(){
        String tmp="";
        if(this.numberPane.getReal1()!=""){
            tmp=tmp+this.numberPane.getReal1();
        }
        if(this.numberPane.getImaginary1()!=""){
            tmp=tmp +"+"+  this.numberPane.getImaginary1() +"i"; 
        }
        if(this.numberPane.getReal2()!=""){
            tmp=tmp + this.operator + this.numberPane.getReal2();
        }
        if(this.numberPane.getImaginary2()!=""){
            tmp=tmp +"+"+  this.numberPane.getImaginary2() +"i"; 
        }
        if(this.calculator.isDone()){
            tmp=tmp +"=" +this.calculator.getResult();
        }
        this.tfData.setText(tmp);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfData = new javax.swing.JTextField();
        numberPane = new complexmathbinarycalculator.NumberPane();
        operationPane = new complexmathbinarycalculator.OperationPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complex Math Binary Calculator");
        setResizable(false);

        tfData.setAutoscrolls(false);
        tfData.setFocusable(false);
        tfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tfData, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operationPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Window window=new Window();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                window.setLocationRelativeTo(null);
                window.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private complexmathbinarycalculator.NumberPane numberPane;
    private complexmathbinarycalculator.OperationPane operationPane;
    public javax.swing.JTextField tfData;
    // End of variables declaration//GEN-END:variables
    private int state;
    private Calculator calculator;
    private String tfString;
    private String real1,
                   real2,
                   imaginary1,
                   imaginary2,
                   operator;
}
